name: Build on release
on:
  release:
    types: created

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package
        run: |
          cd Community.PowerToys.Run.Plugin.JetbrainsProjects
          dotnet pack -p:Platform=x64
          dotnet pack -p:Platform=ARM64

      - name: Upload x64 To Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: Community.PowerToys.Run.Plugin.JetbrainsProjects/bin/JetbrainsProjects_x64.zip
          asset_name: JetbrainsProjects_x64.zip

      - name: Upload ARM64 To Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: Community.PowerToys.Run.Plugin.JetbrainsProjects/bin/JetbrainsProjects_ARM64.zip
          asset_name: JetbrainsProjects_ARM64.zip
