name: Build on release
on:
#  release:
#    types: created
  # manually trigger the workflow
  workflow_dispatch:
    

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Extract version
        id: extract_version
        run: |
          $jsonContent = Get-Content -Path "Community.PowerToys.Run.Plugin.JetbrainsProjects\plugin.json" -Raw
          $jsonObject = $jsonContent | ConvertFrom-Json
          $version = $jsonObject.Version
          echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          
      - name: Package to zip
        run: |
          cd Community.PowerToys.Run.Plugin.JetbrainsProjects
          dotnet pack -p:Platform=x64
          dotnet pack -p:Platform=ARM64
          
      - name: rename zips
        run: |
          cd Community.PowerToys.Run.Plugin.JetbrainsProjects
          Rename-Item -Path bin\JetbrainsProjects_x64.zip -NewName "JetbrainsProjects-${{ env.VERSION }}-x64.zip"
          Rename-Item -Path bin\JetbrainsProjects_ARM64.zip -NewName "JetbrainsProjects-${{ env.VERSION }}-arm64.zip"
          
      - name: create notes
        run: |
          cd Community.PowerToys.Run.Plugin.JetbrainsProjects
          $version = "${{ env.VERSION }}"
          $name = "JetbrainsProjects"
          $projectUri = "https://github.com/eliasblume/powertoys-run-jetbrains-projects"
          $result = "release.md"
          ./create-release-notes.ps1 -version $version -name $name -projectUri $projectUri -result $result
         
 
      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          makeLatest: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: 'Community.PowerToys.Run.Plugin.JetbrainsProjects\bin\*.zip'
          artifactContentType: 'application/zip'
          bodyFile: 'Community.PowerToys.Run.Plugin.JetbrainsProjects/release.md'
            
