name: Build on release
on:
#  release:
#    types: created
  # manually trigger the workflow
  workflow_dispatch:
    

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: go to the project folder
        run: cd Community.PowerToys.Run.Plugin.JetbrainsProjects
        
      - name: Extract version
        id: get_version
        run: |
          $jsonContent = Get-Content -Path "Community.PowerToys.Run.Plugin.JetbrainsProjects\plugin.json" -Raw
          $jsonObject = $jsonContent | ConvertFrom-Json
          $version = $jsonObject.Version
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "Extracted version: $version"

      - name: Package to zip
        run: |
          dotnet pack -p:Platform=x64
          dotnet pack -p:Platform=ARM64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.env.VERSION }}
          release_name: v${{ github.env.VERSION }}
          draft: false
          prerelease: false
      
      
      - name: Upload Release Asset x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Community.PowerToys.Run.Plugin.JetbrainsProjects\bin\JetbrainsProjects_x64.zip
          asset_name: JetbrainsProjects-${{ github.env.VERSION }}-x64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset ARM64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Community.PowerToys.Run.Plugin.JetbrainsProjects\bin\JetbrainsProjects_ARM64.zip
          asset_name: JetbrainsProjects-${{ github.env.VERSION }}-arm64.zip
          asset_content_type: application/zip