name: Build on release
on:
#  release:
#    types: created
  # manually trigger the workflow
  workflow_dispatch:
    

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Extract version
        id: extract_version
        run: |
          $jsonContent = Get-Content -Path "Community.PowerToys.Run.Plugin.JetbrainsProjects\plugin.json" -Raw
          $jsonObject = $jsonContent | ConvertFrom-Json
          $version = $jsonObject.Version
          echo "VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          
      - name: log version
        run: |
          echo "Version: ${{ env.VERSION }}"

      - name: Package to zip
        run: |
          cd Community.PowerToys.Run.Plugin.JetbrainsProjects
          dotnet pack -p:Platform=x64
          dotnet pack -p:Platform=ARM64
          
      - name: rename zips
        run: |
          Rename-Item -Path Community.PowerToys.Run.Plugin.JetbrainsProjects\bin\JetbrainsProjects_x64.zip -NewName "JetbrainsProjects-${{ env.VERSION }}-x64.zip"
          Rename-Item -Path Community.PowerToys.Run.Plugin.JetbrainsProjects\bin\JetbrainsProjects_ARM64.zip -NewName "JetbrainsProjects-${{ env.VERSION }}-arm64.zip"
 
      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          makeLatest: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: 'Community.PowerToys.Run.Plugin.JetbrainsProjects\bin\*.zip'
            
            
      
      
#      - name: Upload Release Asset x64
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: Community.PowerToys.Run.Plugin.JetbrainsProjects\bin\JetbrainsProjects_x64.zip
#          asset_name: JetbrainsProjects-${{ github.env.VERSION }}-x64.zip
#          asset_content_type: application/zip
#
#      - name: Upload Release Asset ARM64
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: Community.PowerToys.Run.Plugin.JetbrainsProjects\bin\JetbrainsProjects_ARM64.zip
#          asset_name: JetbrainsProjects-${{ github.env.VERSION }}-arm64.zip
#          asset_content_type: application/zip